codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 82%           # Cible actuelle
        threshold: 2%         # Tolérance de 2% de baisse
        if_ci_failed: error

    patch:
      default:
        target: 80%           # Coverage minimum pour les nouvelles modifications
        threshold: 5%
        if_ci_failed: error

  ignore:
    # Fichiers à exclure du coverage (comme dans vitest.config.ts)
    - "**/*.config.{ts,js}"
    - "**/*.d.ts"
    - "**/types.ts"
    - "src/types/**/*"
    - "src/**/prisma.ts"
    - "src/lib/gemini.ts"
    - "src/app/lib/ai-actions.ts"
    - "src/app/**/page.tsx"
    - "src/app/**/layout.tsx"
    - "src/app/icon.tsx"
    - "src/components/**/*.tsx"
    - "src/app/boards/**/*.tsx"
    - "prisma/**/*"
    - "public/**/*"
    - "scripts/**/*"
    - ".next/**/*"
    - "node_modules/**/*"
    - "tests/**/*"
    - "playwright-report/**/*"
    - "coverage/**/*"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Annotations pour montrer le coverage dans les PRs
github_checks:
  annotations: true
